name: Send Reminders

on:
  schedule:
    - cron: "*/5 * * * *"   # runs every 5 minutes
  workflow_dispatch:         # allows you to run manually from GitHub UI

jobs:
  send-reminders:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run reminder script
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}   # ✅ Use your Render Postgres URL here
        run: |
          python send_reminders.py
